services:
  mongodb:
    image: mongo:latest
    container_name: t3-chat-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: chat
    ports:
      - 27017:27017
    volumes:
      - /tmp/mongo-data:/data/db
