[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
futures = "0.3.31"
reqwest = { version = "0.12.19", features = ["json", "stream"] }
reqwest-eventsource = "0.6.0"
serde_json = "1.0.140"
anyhow = "1.0.98"
